services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
            - postgres16:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data  
    web:
        build: .
        image: rails-commerce:latest
        container_name: rails-commerce
        user: "${UID:-1000}:${GID:-1000}"
        depends_on:
            - db
            - redis
        volumes:
            - .:/rails:cached
        env_file:
            - ./.env
        ports:
            - '3000:3000'
    test:
        build: .
        user: "${UID:-1000}:${GID:-1000}"
        command: bundle exec rspec
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis
volumes:
    postgres16:
    redis_data: